"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const cors_1 = __importDefault(require("cors"));
const dotenv_1 = __importDefault(require("dotenv"));
const health_route_1 = __importDefault(require("./routes/health.route"));
const auth_route_1 = __importDefault(require("./routes/auth.route"));
const room_route_1 = __importDefault(require("./routes/room.route"));
const tenant_route_1 = __importDefault(require("./routes/tenant.route"));
const contract_route_1 = __importDefault(require("./routes/contract.route"));
const dashboard_route_1 = __importDefault(require("./routes/dashboard.route"));
const notification_route_1 = __importDefault(require("./routes/notification.route"));
const report_route_1 = __importDefault(require("./routes/report.route"));
const audit_route_1 = __importDefault(require("./routes/audit.route"));
const user_route_1 = __importDefault(require("./routes/user.route"));
const my_room_route_1 = __importDefault(require("./routes/my-room.route"));
const invoice_route_1 = __importDefault(require("./routes/invoice.route"));
const maintenance_route_1 = __importDefault(require("./routes/maintenance.route"));
dotenv_1.default.config({ path: '../.env' });
const cron_1 = require("./jobs/cron");
(0, cron_1.initCronJobs)();
const app = (0, express_1.default)();
const port = process.env.PORT || 5000;
app.use((0, cors_1.default)({ origin: true, credentials: true }));
app.use(express_1.default.json());
app.use(express_1.default.urlencoded({ extended: true }));
app.use('/api/health', health_route_1.default);
app.use('/api/auth', auth_route_1.default);
app.use('/api/rooms', room_route_1.default);
app.use('/api/tenants', tenant_route_1.default);
app.use('/api/contracts', contract_route_1.default);
app.use('/api/dashboard', dashboard_route_1.default);
app.use('/api/notifications', notification_route_1.default);
app.use('/api/reports', report_route_1.default);
app.use('/api/audit-logs', audit_route_1.default);
app.use('/api/users', user_route_1.default);
app.use('/api/my-room', my_room_route_1.default);
app.use('/api/invoices', invoice_route_1.default);
app.use('/api/maintenance', maintenance_route_1.default);
app.listen(port, () => {
    console.log(`[Server]: Backend is running at http://localhost:${port}`);
});
